[build]
  command = "npm run prebuild && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://api.misqabbigh.com/api/v1"

[context.deploy-preview.environment]
  VITE_API_URL = "https://dev.misqabbigh.com/api/v1"

[context.development.environment]
  VITE_API_URL = "https://dev.misqabbigh.com/api/v1"
